### ISSUE TITLE
Create evaluation criteria for Workbench messaging functionality

### ISSUE THREAD

**Issue by bdolor** [bcgov/sae-workbench#1]
### Conditions of Satisfaction
- should accurately reflect differences between alternatives

**Comment by pripley123** [comment]
FIrst crack at it, comments / suggestions welcome.

CriteriaID | Category | Criteria | Prioritization
-- | -- | -- | --
C1 | Cost | Product provides   good value for the cost | n/a
C2 | Maintainability | Product is well   maintained / supported / and has strong community support | Should have
C3 | Licensing | Product is open   source | Nice to have
C4 | Functional   requirement | Integration w/   A2MS solution | Must have
C5 | Functional   requirement | Private messaging   b/w individual researchers on a project team | Must have
C6 | Functional   requirement | Project team   messaging (i.e., researcher can send a group message to their project team | Must have
C7 | Functional   requirement | Ability for admin   to audit a researcher's messages | Should have
C8 | Functional   requirement | Email notification   of new messages | Nice to have
C9 | Business rule | Researchers must   be prevented from cross project messaging | Must have
C10 | Business rule | Researchers must   only see messages for the project they have logged in as | Must have

**Comment by pripley123** [comment]
Additional criteria:

C11 | Technical | Product can run in   a Kubernetes / OpenShift | Must have
-- | -- | -- | --

**Comment by pripley123** [comment]
a few more criteria:
C12	Presentation	White labelling	Nice to have
C13	Legal	Must be compliant with privacy laws	Must have
C14	Technical	API access	Must have
C15	Functional requirement	Keeping formatting of code when copying and pasting	Nice to have
C16	Functional requirement	See presence of team members	Nice to have
